### ISSUE TITLE
Cannot update using HACS

### ISSUE THREAD

**Issue by ASchneiderBR** [bbbenji/synthwave-hass#23] opened 2020-03-05 11:22 UTC
Hello! Thanks for creating this great theme.

I cannot update to the latest version using HACS, I get this error message:

```Repository is archived.```

I have now this white bar on top of my dashboard...

![image](https://user-images.githubusercontent.com/25224882/75977211-a6960900-5eba-11ea-920a-51efc4118b1f.png)

Thanks!

**Comment by bbbenji** [comment] 2020-03-05 11:27
What version of the theme are you currently on? 0.2.3 was bugged. 0.2.4 should work well. If you can't update, might be an issue with HACS. For example at the moment I cannot update HACS itself. I am stuck on 0.22.1.

**Comment by ASchneiderBR** [comment] 2020-03-05 11:29
Hello! I am stuck on this version:

![image](https://user-images.githubusercontent.com/25224882/75977477-40f64c80-5ebb-11ea-94cc-51c4deecdffa.png)

I'm having this issue for a couple of days now, I was able to update HACS an other components yesterday, restarted HA, nothing works.

**Comment by bbbenji** [comment] 2020-03-05 11:30
If you are running the latest HA you have to run the latest version of this theme. If you cannot upgrade via HACS you can try doing it manually. I think you not being able to upgrade is a problem with HACS itself.

**Comment by bbbenji** [comment] 2020-03-05 11:39
Appears to be related: https://github.com/hacs/integration/issues/990

**Comment by ASchneiderBR** [comment] 2020-03-05 15:15
Will wait for a fix.

I actually get those errors:

![image](https://user-images.githubusercontent.com/25224882/75995309-fedd0300-5eda-11ea-9af0-d127eae52485.png)

Thanks.

**Comment by ASchneiderBR** [comment] 2020-03-07 22:08
Solved: https://github.com/hacs/integration/releases/tag/0.22.3

**Comment by ASchneiderBR** [comment] 2020-03-09 12:51
Hello again! I'm afraid this problem was not fixed. I've closed this issue when HACS was updated and version 0.3 of this theme was release, did not tested it.

It still white at the top:

![image](https://user-images.githubusercontent.com/25224882/76214388-651f9980-61eb-11ea-91c8-93955b256015.png)

Running latest HACS and theme version:

![image](https://user-images.githubusercontent.com/25224882/76214459-8d0efd00-61eb-11ea-8373-d678359e4d8c.png)

Cleared browser cache as well.

Thanks.

**Comment by bbbenji** [comment] 2020-03-09 12:55
What version of Home Assistant are you running? I cannot reproduce this issue on v0.106.*.

**Comment by ASchneiderBR** [comment] 2020-03-09 12:58
> What version of Home Assistant are you running? I cannot reproduce this issue on v0.106.*.

Hello sir!

Latest version: 0.106.5

**Comment by ASchneiderBR** [comment] 2020-03-09 13:00
I've noticed that the page loads correctly at first, then it shrinks and shows a white banner. I'm running Custom Compact Header, a deprecated addon, I think that's why it "shrinks", since `compact header` option is enabled. Maybe it is related?

**Comment by ASchneiderBR** [comment] 2020-03-09 13:02
Disabling it did not solved:

![image](https://user-images.githubusercontent.com/25224882/76215220-0ce99700-61ed-11ea-9989-1705989ae647.png)

**Comment by bbbenji** [comment] 2020-03-09 13:09
I am using the replacement https://github.com/maykar/custom-header

However, even after disabling custom-header I am unable to reproduce your problem. Until I can, I cannot help fix this. Perhaps you could have a closer look and figure it out?

Can you try another browser? What browser are you currently using?

**Comment by ASchneiderBR** [comment] 2020-03-09 13:49
Well, that's super weird haha

Edge browser:

![image](https://user-images.githubusercontent.com/25224882/76218793-9603cc80-61f3-11ea-905f-e278499fdee6.png)

Will investigate it further...

**Comment by bbbenji** [comment] 2020-04-16 17:45
Closing as the original issue has been resolved in HACS itself a while ago. For any unrelated problems, please create a new issue.

**Closed as completed by bbbenji** 2020-04-16 17:45 UTC
